[build]
builder = "NIXPACKS"
buildCommand = "uv sync --no-dev && rm -f package-lock.json && npm install && npm run deploy"

[deploy]
startCommand = "uv run uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
