[build]
builder = "NIXPACKS"
buildCommand = "rm -f package-lock.json && npm install && npm run deploy"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
